import Head from "next/head";

type Props = {
  title: string;
};

const HeadTitle = ({ title }: Props) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by @nkjy" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default HeadTitle;
